### ISSUE TITLE
I have a problem with building the img or zip no images to download 

### ISSUE THREAD

**Issue by Failedmush** [kinguser981/TWRP-Recovery-Builder-2024#1]
<img width="735" alt="build" src="https://github.com/user-attachments/assets/ec637cf6-5d79-4d62-9283-f4f7720d80b3">

can you help me fix this issue?

**Comment by kinguser981** [comment]
Check ur devices tree 🌳

**Comment by kinguser981** [comment]
> <img width="735" alt="build" src="https://github.com/user-attachments/assets/ec637cf6-5d79-4d62-9283-f4f7720d80b3">
> 
> 
> can you help me fix this issue?

Check ur devices tree 🌳
